using System.Text.Json;
using RimSearcher.Core;
using RimSearcher.Server;

namespace RimSearcher.Tests;

// 同步的事务性：一个源要么整份换掉并记下状态，要么什么都没发生。
// 真跑 ILSpy 不现实（单个程序集数秒起，失败场景更是没法按需复现），所以走注入的反编译接缝；
// 目录改名与单文件复制同理——跨卷、文件被占用这些真实失败条件在测试里无法稳定复现。
public class SourceSyncTransactionTests : IDisposable
{
    private const string Marker = SourceSyncService.OwnershipMarker;

    private static readonly JsonSerializerOptions StateJsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    private readonly TempWorkspace _workspace = new();

    public void Dispose() => _workspace.Dispose();

    private string Cache => _workspace.Dir("cache");

    private string StatePath => Path.Combine(Cache, "assembly-state.json");

    private string Target => Path.Combine(_workspace.Root, "src");

    private string Staging => Target + ".rimsearcher-staging";

    private string Backup => Target + ".rimsearcher-backup";

    // 名字刻意躲开 AssemblyScanner 的运行时程序集前缀表（System*/Mono* 等会被整个跳过），
    // 内容不同以免被「按内容去重」合成一个
    private ResolvedSources Sources()
    {
        _workspace.WriteFile(Path.Combine("dlls", "Alpha.dll"), "alpha-v1");
        _workspace.WriteFile(Path.Combine("dlls", "Beta.dll"), "beta-v1");

        return new ResolvedSources(
            [new SourcePathEntry
            {
                Name = "Core",
                Path = Target,
                AssemblyPaths = [Path.Combine(_workspace.Root, "dlls")]
            }],
            []);
    }

    // 上一次同步留下的源码树：带归属标记，故同步流程认它是自己的产物
    private void GivenPreviousSources()
    {
        _workspace.WriteFile(Path.Combine("src", Marker), "generated by RimSearcher 0.0.0\n");
        _workspace.WriteFile(Path.Combine("src", "Alpha", "Type.cs"), "old-alpha");
        _workspace.WriteFile(Path.Combine("src", "Beta", "Type.cs"), "old-beta");
    }

    private SourceSyncService Service(
        ResolvedSources sources,
        Func<DecompileRequest, CancellationToken, DecompileOutcome>? decompiler = null,
        Action<string, string>? move = null,
        Action<string, string>? copy = null,
        int historyDepth = 3)
    {
        var config = new AppConfig { SourceHistoryDepth = historyDepth };
        Action<string, string> realCopy = static (from, to) => File.Copy(from, to, overwrite: true);

        return new SourceSyncService(config, sources, Cache)
        {
            Decompiler = decompiler ?? Succeed(),
            MoveDirectory = move ?? Directory.Move,
            CopyFile = copy ?? realCopy
        };
    }

    private static Func<DecompileRequest, CancellationToken, DecompileOutcome> Succeed(string content = "new")
        => (request, _) => Write(request, content);

    private static DecompileOutcome Write(DecompileRequest request, string content)
    {
        Directory.CreateDirectory(request.OutputDirectory);
        File.WriteAllText(Path.Combine(request.OutputDirectory, "Type.cs"), content);

        return new DecompileOutcome
        {
            AssemblyPath = request.AssemblyPath,
            Success = true,
            FileCount = 1
        };
    }

    private static DecompileOutcome Fail(DecompileRequest request, string error)
        => new() { AssemblyPath = request.AssemblyPath, Success = false, Error = error };

    private SyncState ReadState()
        => File.Exists(StatePath)
            ? JsonSerializer.Deserialize<SyncState>(File.ReadAllText(StatePath), StateJsonOptions) ?? new SyncState()
            : new SyncState();

    private static string ReadSource(string root, string assembly)
        => File.ReadAllText(Path.Combine(root, assembly, "Type.cs"));

    // ---- 基线：一次正常的同步 -------------------------------------------------

    [Fact]
    public void Sync_PromotesStagingAndRecordsState()
    {
        var sources = Sources();
        GivenPreviousSources();

        var report = Service(sources).Sync(null);

        Assert.Empty(report.Failures);
        Assert.Equal(["Core"], report.PromotedSources);
        Assert.Equal("new", ReadSource(Target, "Alpha"));
        Assert.Equal("new", ReadSource(Target, "Beta"));

        // 归属标记与 .gitignore 随暂存区一起就位，转正后不该缺
        Assert.True(File.Exists(Path.Combine(Target, Marker)));
        Assert.Contains("*", File.ReadAllText(Path.Combine(Target, ".gitignore")));

        // 暂存区与留底目录都不该留在磁盘上
        Assert.False(Directory.Exists(Staging));
        Assert.False(Directory.Exists(Backup));

        Assert.Contains("Core", ReadState().Sources.Keys);
        Assert.Single(new SourceHistoryStore(Cache, 3).ListVersions("Core"));
    }

    // ---- 缺陷 1：部分程序集失败不得提交残缺源码 ------------------------------

    [Fact]
    public void PartialDecompileFailure_LeavesEverythingUntouched()
    {
        var sources = Sources();
        GivenPreviousSources();

        var report = Service(sources, (request, _) =>
            request.AssemblyPath.EndsWith("Beta.dll", StringComparison.OrdinalIgnoreCase)
                ? Fail(request, "ILSpy blew up")
                : Write(request, "new")).Sync(null);

        // 旧源码原封不动，残缺的那一半没有落地
        Assert.Equal("old-alpha", ReadSource(Target, "Alpha"));
        Assert.Equal("old-beta", ReadSource(Target, "Beta"));
        Assert.False(Directory.Exists(Staging));
        Assert.False(Directory.Exists(Backup));

        // 状态没记 → 下次 Check() 仍然报有变更，失败的内容会被自动重试
        Assert.Empty(ReadState().Sources);
        Assert.Empty(report.PromotedSources);
        Assert.Empty(new SourceHistoryStore(Cache, 3).ListVersions("Core"));

        var failure = Assert.Single(report.Failures);
        Assert.Contains("Beta.dll", failure.Failure);
        Assert.Contains("ILSpy blew up", failure.Failure);
        Assert.Contains("rolled back", failure.Describe());
    }

    [Fact]
    public void PartialDecompileFailure_StillReportsChangesOnTheNextCheck()
    {
        var sources = Sources();
        GivenPreviousSources();

        Service(sources, (request, _) =>
            request.AssemblyPath.EndsWith("Beta.dll", StringComparison.OrdinalIgnoreCase)
                ? Fail(request, "boom")
                : Write(request, "new")).Sync(null);

        Assert.True(Assert.Single(Service(sources).Check().Changes).HasChanges);
    }

    // 一个源失败不该拖累别的源
    [Fact]
    public void OneFailingSource_DoesNotBlockTheOthers()
    {
        _workspace.WriteFile(Path.Combine("dllsA", "Alpha.dll"), "alpha-v1");
        _workspace.WriteFile(Path.Combine("dllsB", "Beta.dll"), "beta-v1");

        var good = Path.Combine(_workspace.Root, "good");
        var bad = Path.Combine(_workspace.Root, "bad");

        var sources = new ResolvedSources(
            [
                new SourcePathEntry
                {
                    Name = "Bad", Path = bad, AssemblyPaths = [Path.Combine(_workspace.Root, "dllsB")]
                },
                new SourcePathEntry
                {
                    Name = "Good", Path = good, AssemblyPaths = [Path.Combine(_workspace.Root, "dllsA")]
                }
            ],
            []);

        var report = Service(sources, (request, _) =>
            request.AssemblyPath.Contains("dllsB", StringComparison.OrdinalIgnoreCase)
                ? Fail(request, "boom")
                : Write(request, "new")).Sync(null);

        Assert.Equal(["Good"], report.PromotedSources);
        Assert.Equal("Bad", Assert.Single(report.Failures).SourceName);
        Assert.Equal("new", ReadSource(good, "Alpha"));
        Assert.False(Directory.Exists(bad));
        Assert.Equal(["Good"], ReadState().Sources.Keys);
    }

    // ---- 缺陷 2：转正失败必须回滚 -------------------------------------------

    [Fact]
    public void PromoteFailure_RollsBackThePreviousSources()
    {
        var sources = Sources();
        GivenPreviousSources();

        var copied = 0;

        var report = Service(sources,
            move: (from, to) =>
            {
                // 暂存区搬到位这一步炸掉，留底改名与回滚照常
                if (from.EndsWith(".rimsearcher-staging", StringComparison.Ordinal))
                    throw new InvalidOperationException("simulated move failure");
                Directory.Move(from, to);
            },
            copy: (from, to) =>
            {
                copied++;
                File.Copy(from, to, overwrite: true);
            }).Sync(null);

        // IOException 之外的异常不该退化成逐文件复制——那是给跨卷/占用留的路
        Assert.Equal(0, copied);

        Assert.Equal("old-alpha", ReadSource(Target, "Alpha"));
        Assert.Equal("old-beta", ReadSource(Target, "Beta"));
        Assert.True(File.Exists(Path.Combine(Target, Marker)));
        Assert.False(Directory.Exists(Backup));
        Assert.False(Directory.Exists(Staging));

        Assert.Empty(ReadState().Sources);
        Assert.Contains("rolled back", Assert.Single(report.Failures).Failure);
    }

    // 留底改名都没成功时绝不能动旧目录：此刻还没有任何退路
    [Fact]
    public void BackupRenameFailure_DoesNotTouchTheTarget()
    {
        var sources = Sources();
        GivenPreviousSources();

        var report = Service(sources, move: (from, to) =>
        {
            if (to.EndsWith(".rimsearcher-backup", StringComparison.Ordinal))
                throw new IOException("target directory is locked");
            Directory.Move(from, to);
        }).Sync(null);

        Assert.Equal("old-alpha", ReadSource(Target, "Alpha"));
        Assert.Empty(ReadState().Sources);
        Assert.Contains("rename the old source directory aside", Assert.Single(report.Failures).Failure);
    }

    // ---- 缺陷 2 续：逐文件复制的退化路径 ------------------------------------

    [Fact]
    public void PerFileCopyFallback_StillPromotesWhenEveryCopySucceeds()
    {
        var sources = Sources();
        GivenPreviousSources();

        var report = Service(sources, move: (from, to) =>
        {
            if (from.EndsWith(".rimsearcher-staging", StringComparison.Ordinal))
                throw new IOException("cross-volume move");
            Directory.Move(from, to);
        }).Sync(null);

        Assert.Empty(report.Failures);
        Assert.Equal(["Core"], report.PromotedSources);
        Assert.Equal("new", ReadSource(Target, "Alpha"));
        Assert.True(File.Exists(Path.Combine(Target, Marker)));
        Assert.False(Directory.Exists(Backup));
    }

    [Fact]
    public void PerFileCopyFailure_FailsTheWholeSourceAndRollsBack()
    {
        var sources = Sources();
        GivenPreviousSources();

        var copied = 0;

        var report = Service(sources,
            move: (from, to) =>
            {
                if (from.EndsWith(".rimsearcher-staging", StringComparison.Ordinal))
                    throw new IOException("cross-volume move");
                Directory.Move(from, to);
            },
            copy: (from, to) =>
            {
                // 复制到一半盘满/被占用：以前这里只记一条 warning 就继续，同步照样报成功
                if (++copied == 2) throw new IOException("disk full");
                File.Copy(from, to, overwrite: true);
            }).Sync(null);

        Assert.Equal("old-alpha", ReadSource(Target, "Alpha"));
        Assert.Equal("old-beta", ReadSource(Target, "Beta"));
        Assert.False(Directory.Exists(Backup));
        Assert.Empty(ReadState().Sources);
        Assert.Empty(new SourceHistoryStore(Cache, 3).ListVersions("Core"));

        var failure = Assert.Single(report.Failures).Failure;
        Assert.Contains("disk full", failure);
        Assert.Contains("rolled back", failure);
    }

    // ---- 缺陷 3：暂存/留底目录不得无条件删除 --------------------------------

    [Fact]
    public void ForeignStagingDirectory_IsRefusedAndKept()
    {
        var sources = Sources();
        GivenPreviousSources();

        var precious = _workspace.WriteFile(
            Path.Combine("src.rimsearcher-staging", "my-notes.txt"), "do not delete me");

        var report = Service(sources).Sync(null);

        // 用户的目录一个字节都没动
        Assert.Equal("do not delete me", File.ReadAllText(precious));
        Assert.Equal("old-alpha", ReadSource(Target, "Alpha"));
        Assert.Empty(ReadState().Sources);

        var failure = Assert.Single(report.Failures).Failure;
        Assert.Contains("staging directory unavailable", failure);
        Assert.Contains(Marker, failure);
    }

    // 带标记的暂存目录是我们自己上次崩掉留下的，可以放心回收
    [Fact]
    public void OwnStagingLeftovers_AreReclaimed()
    {
        var sources = Sources();
        GivenPreviousSources();

        _workspace.WriteFile(Path.Combine("src.rimsearcher-staging", Marker), "generated by RimSearcher\n");
        _workspace.WriteFile(Path.Combine("src.rimsearcher-staging", "Alpha", "Type.cs"), "half-written");

        var report = Service(sources).Sync(null);

        Assert.Empty(report.Failures);
        Assert.Equal("new", ReadSource(Target, "Alpha"));
    }

    [Fact]
    public void ForeignBackupDirectory_IsRefusedAndKept()
    {
        var sources = Sources();
        GivenPreviousSources();

        var precious = _workspace.WriteFile(
            Path.Combine("src.rimsearcher-backup", "my-notes.txt"), "do not delete me");

        var report = Service(sources).Sync(null);

        Assert.Equal("do not delete me", File.ReadAllText(precious));
        Assert.Equal("old-alpha", ReadSource(Target, "Alpha"));
        Assert.Empty(ReadState().Sources);
        Assert.Contains("backup directory unavailable", Assert.Single(report.Failures).Failure);
    }

    // 上一次在「已改名留底、还没搬到位」之间被杀掉：旧源码只剩留底目录里那一份
    [Fact]
    public void AbandonedBackup_IsRecoveredBeforeSyncing()
    {
        var sources = Sources();

        _workspace.WriteFile(Path.Combine("src.rimsearcher-backup", Marker), "generated by RimSearcher\n");
        _workspace.WriteFile(Path.Combine("src.rimsearcher-backup", "Alpha", "Type.cs"), "old-alpha");

        var history = new SourceHistoryStore(Cache, 3);
        var report = Service(sources).Sync(null);

        Assert.Empty(report.Failures);
        Assert.Equal("new", ReadSource(Target, "Alpha"));
        Assert.False(Directory.Exists(Backup));

        // 救回来的那一版成了历史 diff 的基线：Alpha 是「改了」而不是「新增」
        var version = Assert.Single(history.ListVersions("Core"));
        Assert.Equal("old-alpha", history.ReadArchived("Core", version.Id, Path.Combine("Alpha", "Type.cs")));
    }

    // ---- 缺陷 4：状态文件原子替换 -------------------------------------------

    [Fact]
    public void StateWriteFailure_LeavesThePreviousStateReadable()
    {
        var sources = Sources();
        GivenPreviousSources();

        Service(sources).Sync(null);

        var before = File.ReadAllText(StatePath);
        Assert.Contains("Core", before);

        // 临时文件写不出去 = 「写入过程失败」。占住那个名字（建成目录）即可稳定复现，
        // 而原来的 File.WriteAllText 直接写目标文件，同样的失败会把状态文件截成半截。
        Directory.CreateDirectory($"{StatePath}.{Environment.ProcessId}.tmp");

        _workspace.WriteFile(Path.Combine("dlls", "Alpha.dll"), "alpha-v2");
        var report = Service(sources).Sync(null);

        Assert.Equal(["Core"], report.PromotedSources);

        // 旧状态整份还在，且仍能解析
        Assert.Equal(before, File.ReadAllText(StatePath));
        Assert.Contains("Core", ReadState().Sources.Keys);
    }

    [Fact]
    public void StateFile_IsWrittenThroughATemporaryFile()
    {
        var sources = Sources();
        GivenPreviousSources();

        Service(sources).Sync(null);

        // 临时文件必须被换掉而不是留在 cache 目录里
        Assert.Empty(Directory.GetFiles(Cache, "*.tmp"));
        Assert.True(File.Exists(StatePath));
    }

    // ---- 缺陷 5：进程级单写者 -----------------------------------------------

    [Fact]
    public async Task SecondConcurrentSync_IsRefusedInsteadOfQueued()
    {
        var sources = Sources();
        GivenPreviousSources();

        using var entered = new ManualResetEventSlim(false);
        using var release = new ManualResetEventSlim(false);

        var service = Service(sources, (request, _) =>
        {
            entered.Set();
            release.Wait(TimeSpan.FromSeconds(30));
            return Write(request, "new");
        });

        var first = Task.Run(() => service.SyncAsync(null));
        Assert.True(entered.Wait(TimeSpan.FromSeconds(30)), "第一次同步没能进入反编译");

        var second = await service.SyncAsync(null);

        Assert.True(second.AlreadyRunning);
        Assert.Empty(second.Changes);
        Assert.Empty(second.PromotedSources);

        // 被拒的那次绝不能排队等着偷偷再跑一遍
        Assert.False(release.IsSet);

        release.Set();
        var report = await first;

        Assert.Equal(["Core"], report.PromotedSources);
        Assert.False(report.AlreadyRunning);
    }

    [Fact]
    public async Task Lock_IsReleasedSoLaterSyncsStillRun()
    {
        var sources = Sources();
        GivenPreviousSources();

        var service = Service(sources);

        Assert.False((await service.SyncAsync(null)).AlreadyRunning);

        _workspace.WriteFile(Path.Combine("dlls", "Alpha.dll"), "alpha-v2");

        var second = await service.SyncAsync(null);
        Assert.False(second.AlreadyRunning);
        Assert.Equal(["Core"], second.PromotedSources);
    }

    // 取消不该让已经转正的源丢掉状态：磁盘上确实换过内容了
    [Fact]
    public async Task Cancellation_KeepsTheStateOfAlreadyPromotedSources()
    {
        _workspace.WriteFile(Path.Combine("dllsA", "Alpha.dll"), "alpha-v1");
        _workspace.WriteFile(Path.Combine("dllsB", "Beta.dll"), "beta-v1");

        var first = Path.Combine(_workspace.Root, "first");
        var second = Path.Combine(_workspace.Root, "second");

        var sources = new ResolvedSources(
            [
                new SourcePathEntry
                {
                    Name = "First", Path = first, AssemblyPaths = [Path.Combine(_workspace.Root, "dllsA")]
                },
                new SourcePathEntry
                {
                    Name = "Second", Path = second, AssemblyPaths = [Path.Combine(_workspace.Root, "dllsB")]
                }
            ],
            []);

        using var cancellation = new CancellationTokenSource();

        var service = Service(sources, (request, token) =>
        {
            if (request.AssemblyPath.Contains("dllsB", StringComparison.OrdinalIgnoreCase))
            {
                cancellation.Cancel();
                token.ThrowIfCancellationRequested();
            }

            return Write(request, "new");
        });

        await Assert.ThrowsAnyAsync<OperationCanceledException>(
            () => service.SyncAsync(null, cancellation.Token));

        Assert.Equal(["First"], ReadState().Sources.Keys);
        Assert.Equal("new", ReadSource(first, "Alpha"));
        Assert.False(Directory.Exists(second + ".rimsearcher-staging"));
    }
}
